on: [push, pull_request]
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        with:
          version: "0.20.0"

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install "arduino:avr@1.8.4"
          arduino-cli core install "arduino:sam"

      - name: Start Arduino CLI Daemon
        run: arduino-cli daemon --daemonize --port 50051 &

      - name: Install
        run: yarn install --ignore-scripts

      - name: Check
        run: yarn run typecheck

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test
