on: [push, pull_request]
name: linux-build
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        node: ["16"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Install
        run: yarn install --ignore-scripts

      - name: Generate types
        run: yarn run --cwd=packages/deployment-server prisma generate

      - name: Build server type declarations
        run: yarn run --cwd=packages/deployment-server tsc

      - name: Typecheck
        run: yarn run typecheck

      - name: Lint
        run: yarn run lint
