on: [push, pull_request]
name: linux-build
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        node: ["16", "17"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}_node-${{ matrix.node }}
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: deploymentdb
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        with:
          version: "0.20.0"

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install "arduino:avr"
          arduino-cli core install "arduino:sam"

      - name: Start Arduino CLI Daemon
        run: arduino-cli daemon --daemonize --port 50051 &

      - name: Install
        run: yarn install --ignore-scripts

      - name: Migrate
        run: yarn run --cwd=packages/deployment-server prisma migrate deploy

      - name: Generate types
        run: yarn run --cwd=packages/deployment-server prisma generate

      - name: Seed database
        run: yarn run --cwd=packages/deployment-server prisma db seed

      - name: Build server type declarations
        run: yarn run --cwd=packages/deployment-server tsc

      - name: Test
        run: yarn run test
